import ReactQueryProvider from './ReactQueryProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
    <html lang="en">
      <body className={`${inter.className} bg-black text-white w-full min-h-screen items-center justify-center`}>{children}</body>
    </html>
    </ReactQueryProvider>
  )
}
